services:
  - type: web
    name: clase-15-api
    plan: free
    region: oregon
    env: docker
    dockerfilePath: ./Dockerfile
    numInstances: 1
    autoDeploy: true
    deployToRegions:
      - oregon
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: clase-15-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: clase-15-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: clase-15-db
          property: password

databases:
  - name: clase-15-db
    databaseName: clase15
    plan: free
    region: oregon
